// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function GetConfig():Promise<config.Config>;

export function RunCode(arg1:string):Promise<main.RunResult>;

export function SaveConfig(arg1:string,arg2:string):Promise<string>;
